# Generated by Django 5.2.5 on 2025-09-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hrs_ape', models.DateTimeField()),
                ('fech_hrs_cie', models.DateTimeField(blank=True, null=True)),
                ('monto_ini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_caja', models.IntegerField()),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('apellido_cli', models.CharField(max_length=50)),
                ('correo_cli', models.CharField(max_length=255)),
                ('telefono_cli', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_comp', models.IntegerField()),
                ('fecha_hs_comp', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetCompras',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'det_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetVentas',
            fields=[
                ('id_det_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_venta', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'det_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min_prod', models.IntegerField()),
                ('stock_act_prod', models.IntegerField()),
                ('reposicion_prod', models.IntegerField()),
                ('stock_max_prod', models.IntegerField()),
                ('tipo_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'productos_x_proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('tipo_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.CharField(max_length=100)),
                ('nombre_serv', models.CharField(max_length=100)),
                ('precio_serv', models.DecimalField(decimal_places=0, max_digits=9)),
                ('duracion_serv', models.TimeField(blank=True, null=True)),
                ('disponible_serv', models.IntegerField(blank=True, null=True)),
                ('descripcion_serv', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField()),
                ('hora_turno', models.TimeField()),
                ('estado_turno', models.CharField(blank=True, max_length=9, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnosXServicios',
            fields=[
                ('id_turno_servicio', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'turnos_x_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol_usuario', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hs_vent', models.DateTimeField()),
                ('tipo_venta', models.CharField(max_length=100)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
